#!/usr/bin/env python3
"""Regenerate `infra/data/response_examples.md` from the DM archive.

Same input as `extract_tone.py` (the local `infra/data/conversations/*.json`
corpus) but the output is a curated set of anonymized *examples* per
category, not statistics. The goal is to give the next LLM a corpus of
real templates it can adapt when drafting a reply.

Usage
-----
    python3 infra/scripts/extract_response_templates.py
    python3 infra/scripts/extract_response_templates.py --dry-run
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data" / "conversations"
OUT_PATH = ROOT / "data" / "response_examples.md"

# Same classifier logic as extract_tone.py (kept local on purpose — small).
CATEGORIES = {
    "premiere_approche": "Première approche (cold)",
    "reponse_positive": "Réponse à un signal positif",
    "negociation_produits": "Négociation produits / dotation",
    "envoi_code": "Envoi du code affilié",
    "relance": "Relance après silence",
    "sav_light": "Touch SAV léger (ambassadeur)",
    "cloture": "Clôture / bienvenue",
}

EXAMPLES_PER_CATEGORY = 5

CODE_RE = re.compile(r"\b[A-Z]{4,}\b")


_METADATA_FILES = {"_index.json", "_progress.json"}


def _load_corpus() -> List[Dict[str, Any]]:
    return [
        json.loads(p.read_text())
        for p in sorted(DATA_DIR.glob("*.json"))
        if p.name not in _METADATA_FILES
    ]


def _sent_messages(corpus: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    out: List[Dict[str, Any]] = []
    for conv in corpus:
        statut = conv.get("statut_at_download", "")
        for msg in conv.get("messages", []):
            if not msg.get("is_sent_by_viewer"):
                continue
            text = (msg.get("text") or "").strip()
            if not text:
                continue
            out.append({**msg, "_statut": statut, "_username": conv.get("username")})
    return out


def _anonymize(text: str) -> str:
    text = re.sub(r"@\w+", "{username}", text)
    text = re.sub(
        r"\b(Salut|Hello|Coucou|Hey|Yo|Bonjour|Bonsoir)\s+[A-ZÉÈÀÔÎ][a-zéèàôîûç]+\b",
        r"\1 {prenom}",
        text,
    )
    # Replace codes affiliés that look like FIRSTNAME-type codes.
    text = re.sub(r"\b[A-Z]{5,}\b", "{CODE}", text)
    return text


def _classify(msg: Dict[str, Any]) -> str:
    text = msg["text"].lower()
    statut = (msg.get("_statut") or "").lower()
    if CODE_RE.search(msg["text"]) and "code" in text:
        return "envoi_code"
    if any(w in text for w in ["excuse", "désol", "oubli", "probleme", "problème", "retard"]):
        return "sav_light"
    if any(w in text for w in ["taille", "saveur", "whey", "électrolyte", "preworkout"]):
        return "negociation_produits"
    if any(w in text for w in ["des nouvelles", "comment ça", "toujours là", "tjr"]):
        return "relance"
    if any(w in text for w in ["bienvenue", "top départ", "c'est parti", "let's go"]):
        return "cloture"
    if statut == "in-cold":
        return "premiere_approche"
    if any(w in text for w in ["super", "parfait", "nickel", "cool", "top"]):
        return "reponse_positive"
    return ""


def _pick_examples(msgs: List[Dict[str, Any]]) -> Dict[str, List[str]]:
    buckets: Dict[str, List[str]] = {k: [] for k in CATEGORIES}
    for m in msgs:
        cat = _classify(m)
        if cat and cat in buckets:
            buckets[cat].append(_anonymize(m["text"]))
    # Keep medium-length examples, dedup on first 30 chars.
    result: Dict[str, List[str]] = {}
    for cat, items in buckets.items():
        items.sort(key=lambda t: abs(len(t) - 200))
        seen_prefix: set = set()
        curated: List[str] = []
        for item in items:
            key = item[:30].lower()
            if key in seen_prefix:
                continue
            seen_prefix.add(key)
            curated.append(item)
            if len(curated) >= EXAMPLES_PER_CATEGORY:
                break
        result[cat] = curated
    return result


def _format(curated: Dict[str, List[str]]) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    lines: List[str] = []
    lines.append("# Real response examples (anonymized)")
    lines.append("")
    lines.append(
        f"> Auto-generated by `infra/scripts/extract_response_templates.py` on {now}."
    )
    lines.append(
        "> Sourced from `infra/data/conversations/*.json`. Usernames and first names "
        "are replaced by `{username}` / `{prenom}`, codes by `{CODE}`."
    )
    lines.append("")

    for key, title in CATEGORIES.items():
        items = curated.get(key) or []
        lines.append(f"## {title}")
        lines.append("")
        if not items:
            lines.append("_(no examples in corpus)_")
            lines.append("")
            continue
        for ex in items:
            # Use blockquote formatting, preserving multiline replies.
            for line in ex.splitlines() or [ex]:
                lines.append(f"> {line}")
            lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    corpus = _load_corpus()
    if not corpus:
        print(
            f"No conversations found in {DATA_DIR}. Run "
            "`infra/scripts/download_conversations.py` first.",
            file=sys.stderr,
        )
        return 1
    msgs = _sent_messages(corpus)
    curated = _pick_examples(msgs)
    out = _format(curated)

    total_examples = sum(len(v) for v in curated.values())
    print(
        f"Corpus : {len(corpus)} convs, {len(msgs)} sent msgs, "
        f"{total_examples} examples across {len(CATEGORIES)} categories"
    )

    if args.dry_run:
        print("---")
        print(out[:1500])
        print("... [truncated] ...")
        return 0

    if OUT_PATH.exists():
        stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        backup = OUT_PATH.with_suffix(f".md.bak.{stamp}")
        backup.write_text(OUT_PATH.read_text())
        print(f"Backed up previous file → {backup.name}")
    OUT_PATH.write_text(out)
    print(f"Wrote {OUT_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
